language: python
install: "make"
script:
  - make ci
cache: pip
jobs:
  include:
    - stage: test
      python: '2.7'
    - stage: test
      python: '3.5'
    - stage: test
      python: '3.6'
    - stage: test
      python: '3.7' 
    - stage: test
      python: '3.8' 
    - stage: test
      python: 'pypy3'
      dist: xenial
    - stage: test
      python: '3.8'
    - stage: coverage
      python: '3.6'
      script: codecov